/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package market;

import java.sql.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author aflia
 */
public class Barang extends javax.swing.JFrame {
private Connection conn;
private boolean isUpdateEnabled = false;

private void koneksi() {
    try {
        String url = "jdbc:mysql://localhost:3306/market"; // Ganti sesuai konfigurasi database
        String user = "root"; // Username database
        String pass = "1"; // Password database
        conn = DriverManager.getConnection(url, user, pass);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Koneksi ke database gagal: " + e.getMessage());
    }
}

    /**
     * Creates new form About
     */
    public Barang() {
        initComponents();
        koneksi();
    loadData();
    }
    
    private void loadData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Harga Modal");
    model.addColumn("Harga Jual");
    model.addColumn("Kategori");
    model.addColumn("Waktu Pembelian");
    model.addColumn("Jumlah");
    model.addColumn("Satuan");

    try {
        String query = "SELECT * FROM t_barang";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("kode_barang"),
                rs.getString("nama_barang"),
                rs.getInt("harga_modal"),
                rs.getInt("harga_jual"),
                rs.getString("kategori"),
                rs.getString("waktu_pembelian"),
                rs.getInt("jumlah"),
                rs.getString("satuan")
            });
        }

        jTable1.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txHome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txAbout = new javax.swing.JLabel();
        txBarang = new javax.swing.JLabel();
        txSupplier = new javax.swing.JLabel();
        txPenjualan = new javax.swing.JLabel();
        iHome = new javax.swing.JLabel();
        iBarang = new javax.swing.JLabel();
        iSupplier = new javax.swing.JLabel();
        iPenjualan = new javax.swing.JLabel();
        iAbout = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txJumlah = new javax.swing.JTextField();
        cbSatuan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txHrgJual = new javax.swing.JTextField();
        txHrgModal = new javax.swing.JTextField();
        txWaktuBeli = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        txKodeBarang = new javax.swing.JTextField();
        txNamaBarang = new javax.swing.JTextField();
        btCari = new javax.swing.JButton();
        btInput = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        txCari = new javax.swing.JTextField();
        btClear = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        latar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(184, 212, 173));
        jPanel2.setLayout(null);

        txHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txHomeMouseClicked(evt);
            }
        });
        jPanel2.add(txHome);
        txHome.setBounds(0, 110, 150, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.keranjang.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 10, 120, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/garis0.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 90, 110, 10);

        txAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txAboutMouseClicked(evt);
            }
        });
        jPanel2.add(txAbout);
        txAbout.setBounds(0, 270, 150, 40);

        txBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txBarangMouseClicked(evt);
            }
        });
        jPanel2.add(txBarang);
        txBarang.setBounds(0, 150, 150, 40);

        txSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txSupplierMouseClicked(evt);
            }
        });
        jPanel2.add(txSupplier);
        txSupplier.setBounds(0, 190, 150, 40);

        txPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txPenjualanMouseClicked(evt);
            }
        });
        jPanel2.add(txPenjualan);
        txPenjualan.setBounds(0, 230, 150, 40);

        iHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.Icon1.png"))); // NOI18N
        jPanel2.add(iHome);
        iHome.setBounds(10, 100, 40, 50);

        iBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.barang.png"))); // NOI18N
        jPanel2.add(iBarang);
        iBarang.setBounds(0, 130, 50, 70);

        iSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.supplier.png"))); // NOI18N
        jPanel2.add(iSupplier);
        iSupplier.setBounds(0, 180, 50, 60);

        iPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/penjualan.icon1.png"))); // NOI18N
        jPanel2.add(iPenjualan);
        iPenjualan.setBounds(0, 230, 50, 40);

        iAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.about1.png"))); // NOI18N
        jPanel2.add(iAbout);
        iAbout.setBounds(0, 260, 50, 70);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 496));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Data Barang");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Kode:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 40, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("Harga Modal:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("Waktu Pembelian:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("Jumlah:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText("Nama Barang:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setText("Harga Jual:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setText("Kategori:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));
        jPanel1.add(txJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 230, 30));

        cbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "kg", "pcs", "liter" }));
        jPanel1.add(cbSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 340, 640, 140));

        txHrgJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHrgJualActionPerformed(evt);
            }
        });
        jPanel1.add(txHrgJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 310, 30));

        txHrgModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHrgModalActionPerformed(evt);
            }
        });
        jPanel1.add(txHrgModal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 250, 30));
        jPanel1.add(txWaktuBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 250, 30));

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Penjualan Ritel", "Ritel" }));
        cbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(cbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 310, 30));
        jPanel1.add(txKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 250, 30));
        jPanel1.add(txNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 310, 30));

        btCari.setText("Search");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });
        jPanel1.add(btCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 70, -1));

        btInput.setText("Input");
        btInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInputActionPerformed(evt);
            }
        });
        jPanel1.add(btInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 70, -1));

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 70, -1));

        btHapus.setText("Delete");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 70, -1));

        txCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCariActionPerformed(evt);
            }
        });
        jPanel1.add(txCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 130, -1));

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel1.add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        jPanel1.add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        latar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/latarbelakang1.png"))); // NOI18N
        jPanel1.add(latar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 750, 520));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 810, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 496));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txHomeMouseClicked
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txHomeMouseClicked

    private void txBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txBarangMouseClicked
        // TODO add your handling code here:
        Barang barang = new Barang();
        barang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txBarangMouseClicked

    private void txSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txSupplierMouseClicked
        // TODO add your handling code here:
        Supplier supplier = new Supplier();
        supplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txSupplierMouseClicked

    private void txPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txPenjualanMouseClicked
        // TODO add your handling code here:
        Penjualan penjualan = new Penjualan();
        penjualan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txPenjualanMouseClicked

    private void txAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txAboutMouseClicked
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txAboutMouseClicked

    private void txHrgModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHrgModalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHrgModalActionPerformed

    private void txHrgJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHrgJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHrgJualActionPerformed

    private void cbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKategoriActionPerformed

    private void btInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInputActionPerformed
        // TODO add your handling code here:                                         
        String kode = txKodeBarang.getText();
        String nama = txNamaBarang.getText();
        int hargaModal = Integer.parseInt(txHrgModal.getText());
        int hargaJual = Integer.parseInt(txHrgJual.getText());
        String kategori = cbKategori.getSelectedItem().toString();
        String waktu = txWaktuBeli.getText();
        int jumlah = Integer.parseInt(txJumlah.getText());
        String satuan = cbSatuan.getSelectedItem().toString();

    try {
        String query = "INSERT INTO t_barang (kode_barang, nama_barang, harga_modal, harga_jual, kategori, waktu_pembelian, jumlah, satuan) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, kode);
        pst.setString(2, nama);
        pst.setInt(3, hargaModal);
        pst.setInt(4, hargaJual);
        pst.setString(5, kategori);
        pst.setString(6, waktu);
        pst.setInt(7, jumlah);
        pst.setString(8, satuan);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
        loadData(); // Perbarui tabel setelah input
        clearForm(); // Hapus isi form
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    }


    }//GEN-LAST:event_btInputActionPerformed
        private void clearForm() {
    txKodeBarang.setText("");
    txNamaBarang.setText("");
    txHrgModal.setText("");
    txHrgJual.setText("");
    cbKategori.setSelectedIndex(0);
    txWaktuBeli.setText("");
    txJumlah.setText("");
    cbSatuan.setSelectedIndex(0);
}

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        if (txKodeBarang.getText().isEmpty() || 
        txNamaBarang.getText().isEmpty() || 
        txHrgModal.getText().isEmpty() || 
        txHrgJual.getText().isEmpty() || 
        txJumlah.getText().isEmpty() || 
        txWaktuBeli.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Semua field harus diisi.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        String kode = txKodeBarang.getText();
        String nama = txNamaBarang.getText();
        int hargaModal = Integer.parseInt(txHrgModal.getText());
        int hargaJual = Integer.parseInt(txHrgJual.getText());
        String kategori = cbKategori.getSelectedItem().toString();
        String waktu = txWaktuBeli.getText();
        int jumlah = Integer.parseInt(txJumlah.getText());
        String satuan = cbSatuan.getSelectedItem().toString();
        
        // Execute the update query
        String query = "UPDATE t_barang SET nama_barang = ?, harga_modal = ?, harga_jual = ?, kategori = ?, waktu_pembelian = ?, jumlah = ?, satuan = ? WHERE kode_barang = ?";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, nama);
        pst.setInt(2, hargaModal);
        pst.setInt(3, hargaJual);
        pst.setString(4, kategori);
        pst.setString(5, waktu);
        pst.setInt(6, jumlah);
        pst.setString(7, satuan);
        pst.setString(8, kode);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.");
        loadData();
        clearForm();
        isUpdateEnabled = false; // Reset update status
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap masukkan angka yang valid untuk harga dan jumlah.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage());
    }
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        // TODO add your handling code here:
        String keyword = txCari.getText().trim();

    if (keyword != null && !keyword.isEmpty()) {
        try {
            // Kueri SQL untuk mencari data berdasarkan kode_barang, nama_barang, atau kategori
            String query = "SELECT * FROM t_barang WHERE kode_barang LIKE ? OR nama_barang LIKE ? OR kategori LIKE ?";
            PreparedStatement pst = conn.prepareStatement(query);

            // Mengisi parameter kueri dengan keyword
            pst.setString(1, "%" + keyword + "%");
            pst.setString(2, "%" + keyword + "%");
            pst.setString(3, "%" + keyword + "%");

            ResultSet rs = pst.executeQuery();

            // Memuat hasil pencarian ke dalam tabel
            loadData(rs);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mencari data: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan masukkan kata kunci untuk pencarian.");
    }
    }//GEN-LAST:event_btCariActionPerformed

    private void loadData(ResultSet rs) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing data

    try {
        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("kode_barang"),
                rs.getString("nama_barang"),
                rs.getDouble("harga_modal"),
                rs.getDouble("harga_jual"),
                rs.getString("kategori"),
                rs.getString("waktu_pembelian"),
                rs.getInt("jumlah"),
                rs.getString("satuan")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}

    
    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        String kode = txKodeBarang.getText();

    if (kode.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Kode barang tidak boleh kosong.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            String query = "DELETE FROM t_barang WHERE kode_barang = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, kode);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            loadData();
            clearForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btHapusActionPerformed

    private void txCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCariActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (!isUpdateEnabled) {
        JOptionPane.showMessageDialog(this, "Klik tombol Edit terlebih dahulu untuk memilih data.");
        return; // Hentikan proses lebih lanjut
    }
        
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        // Retrieve data from the selected row
        String kode = jTable1.getValueAt(selectedRow, 0).toString();
        String nama = jTable1.getValueAt(selectedRow, 1).toString();
        String hargaModal = jTable1.getValueAt(selectedRow, 2).toString();
        String hargaJual = jTable1.getValueAt(selectedRow, 3).toString();
        String kategori = jTable1.getValueAt(selectedRow, 4).toString();
        String waktu = jTable1.getValueAt(selectedRow, 5).toString();
        String jumlah = jTable1.getValueAt(selectedRow, 6).toString();
        String satuan = jTable1.getValueAt(selectedRow, 7).toString();
        
        // Populate form fields with the selected row's data
        txKodeBarang.setText(kode);
        txNamaBarang.setText(nama);
        txHrgModal.setText(hargaModal);
        txHrgJual.setText(hargaJual);
        cbKategori.setSelectedItem(kategori);
        txWaktuBeli.setText(waktu);
        txJumlah.setText(jumlah);
        cbSatuan.setSelectedItem(satuan);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
    txKodeBarang.setText("");
    txNamaBarang.setText("");
    txHrgModal.setText("");
    txHrgJual.setText("");
    cbKategori.setSelectedIndex(0);
    txWaktuBeli.setText("");
    txJumlah.setText("");
    cbSatuan.setSelectedIndex(0);

    // Jika ada komponen lain seperti combo box, reset nilainya
    // comboBoxKategori.setSelectedIndex(0); // Contoh jika ada combo box
    
    }//GEN-LAST:event_btClearActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        isUpdateEnabled = true;
    JOptionPane.showMessageDialog(this, "Anda sekarang dapat memilih data dari tabel.");
    }//GEN-LAST:event_btEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btCari;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btInput;
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbSatuan;
    private javax.swing.JLabel iAbout;
    private javax.swing.JLabel iBarang;
    private javax.swing.JLabel iHome;
    private javax.swing.JLabel iPenjualan;
    private javax.swing.JLabel iSupplier;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel latar;
    private javax.swing.JLabel txAbout;
    private javax.swing.JLabel txBarang;
    private javax.swing.JTextField txCari;
    private javax.swing.JLabel txHome;
    private javax.swing.JTextField txHrgJual;
    private javax.swing.JTextField txHrgModal;
    private javax.swing.JTextField txJumlah;
    private javax.swing.JTextField txKodeBarang;
    private javax.swing.JTextField txNamaBarang;
    private javax.swing.JLabel txPenjualan;
    private javax.swing.JLabel txSupplier;
    private javax.swing.JTextField txWaktuBeli;
    // End of variables declaration//GEN-END:variables
}
