/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package market;

/**
 *
 * @author aflia
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txHome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txAbout = new javax.swing.JLabel();
        txBarang = new javax.swing.JLabel();
        txSupplier = new javax.swing.JLabel();
        txPenjualan = new javax.swing.JLabel();
        iHome = new javax.swing.JLabel();
        iBarang = new javax.swing.JLabel();
        iSupplier = new javax.swing.JLabel();
        iPenjualan = new javax.swing.JLabel();
        iAbout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shadow.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(184, 212, 173));
        jPanel2.setLayout(null);

        txHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txHomeMouseClicked(evt);
            }
        });
        jPanel2.add(txHome);
        txHome.setBounds(0, 110, 150, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.keranjang.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 10, 120, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/garis0.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 90, 110, 10);

        txAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txAboutMouseClicked(evt);
            }
        });
        jPanel2.add(txAbout);
        txAbout.setBounds(0, 270, 150, 40);

        txBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txBarangMouseClicked(evt);
            }
        });
        jPanel2.add(txBarang);
        txBarang.setBounds(0, 150, 150, 40);

        txSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txSupplierMouseClicked(evt);
            }
        });
        jPanel2.add(txSupplier);
        txSupplier.setBounds(0, 190, 150, 40);

        txPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txPenjualanMouseClicked(evt);
            }
        });
        jPanel2.add(txPenjualan);
        txPenjualan.setBounds(0, 230, 150, 40);

        iHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.Icon1.png"))); // NOI18N
        jPanel2.add(iHome);
        iHome.setBounds(10, 100, 40, 50);

        iBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.barang.png"))); // NOI18N
        jPanel2.add(iBarang);
        iBarang.setBounds(0, 130, 50, 70);

        iSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.supplier.png"))); // NOI18N
        jPanel2.add(iSupplier);
        iSupplier.setBounds(0, 180, 50, 60);

        iPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/penjualan.icon1.png"))); // NOI18N
        jPanel2.add(iPenjualan);
        iPenjualan.setBounds(0, 230, 50, 40);

        iAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.about1.png"))); // NOI18N
        jPanel2.add(iAbout);
        iAbout.setBounds(0, 260, 50, 70);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 496));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo Welcome[1].png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 450, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gambariconsamping1-transformed1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -4, 290, 500));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 810, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 496));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txHomeMouseClicked
        // TODO add your handling code here:
        Dashboard home = new Dashboard();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txHomeMouseClicked

    private void txBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txBarangMouseClicked
        // TODO add your handling code here:
        Barang barang = new Barang();
        barang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txBarangMouseClicked

    private void txSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txSupplierMouseClicked
        // TODO add your handling code here:
        Supplier supplier = new Supplier();
        supplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txSupplierMouseClicked

    private void txPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txPenjualanMouseClicked
        // TODO add your handling code here:
        Penjualan penjualan = new Penjualan();
        penjualan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txPenjualanMouseClicked

    private void txAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txAboutMouseClicked
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txAboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel iAbout;
    private javax.swing.JLabel iBarang;
    private javax.swing.JLabel iHome;
    private javax.swing.JLabel iPenjualan;
    private javax.swing.JLabel iSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txAbout;
    private javax.swing.JLabel txBarang;
    private javax.swing.JLabel txHome;
    private javax.swing.JLabel txPenjualan;
    private javax.swing.JLabel txSupplier;
    // End of variables declaration//GEN-END:variables
}
