/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package market;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;

/**
 *
 * @author aflia
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progress = new javax.swing.JProgressBar();
        organiclife = new javax.swing.JLabel();
        load = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        menunggu = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        progress.setBackground(new java.awt.Color(255, 255, 255));
        progress.setForeground(new java.awt.Color(155, 200, 139));
        progress.setValue(36);
        progress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 171, 76), 3));
        jPanel1.add(progress);
        progress.setBounds(50, 230, 310, 20);

        organiclife.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        organiclife.setForeground(new java.awt.Color(60, 94, 47));
        organiclife.setText("Organic Life");
        jPanel1.add(organiclife);
        organiclife.setBounds(140, 140, 120, 30);

        load.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        load.setForeground(new java.awt.Color(66, 107, 77));
        load.setText("36%");
        jPanel1.add(load);
        load.setBounds(190, 200, 30, 20);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconMarket..png"))); // NOI18N
        jPanel1.add(icon);
        icon.setBounds(150, 30, 110, 110);

        menunggu.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        menunggu.setForeground(new java.awt.Color(66, 107, 77));
        menunggu.setText("Mohon Tunggu....");
        jPanel1.add(menunggu);
        menunggu.setBounds(160, 260, 120, 18);

        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/360_F_135628942_wAZhAFbDfQpTI533KoCSG3Vq9YfuSA8F[1].jpg"))); // NOI18N
        background.setText("jLabel1");
        jPanel1.add(background);
        background.setBounds(-20, -20, 450, 330);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    // Membuat instance splash screen
    Splash splash = new Splash();
    splash.setVisible(true); // Tampilkan splash screen

    try {
        // Proses pengisian progress bar
        for (int i = 0; i <= 100; i++) {
            Thread.sleep(30); // Waktu delay dalam milidetik
            splash.progress.setValue(i); // Update nilai progress bar
            splash.load.setText(i + "%"); // Update label persentase
        }
    } catch (Exception e) {
        e.printStackTrace(); // Log jika terjadi error
    }

    // Setelah progress bar selesai
    splash.dispose(); // Tutup splash screen

    // Membuka menu utama atau form Dashboard
    Login login = new Login(); // Ganti dengan form utama Anda
    login.setVisible(true); // Tampilkan form utama
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel load;
    private javax.swing.JLabel menunggu;
    private javax.swing.JLabel organiclife;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
